# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a634c51567cd61b32d909a126948adf859cff93ae067a3c1ea8af88e10a5a4c558722b55bf32ab65a526fa31498cfbf21240043f0ad85fef1e989f8953d5adc7

test:
  secret_key_base: 38cede8e3c3a2d4b216c5b90e9f61b639e7fc77ad9d36d057f70ab1039b80cd60f829c3c90b7c9e640a096c67f5bfcfc94432b2244fb95d0d67934e9c4e33d78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
